---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dependabot"
    commit-message:
      prefix: "ci(deps): "

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dependabot"
    commit-message:
      prefix: "chore(deps): "
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
